{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-12T19:47:54Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-test-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-test-bot
    message: |
      fix: lets not wait for pods to be ready to verify jobs

      as a pod may never be ready but may be running so lets log earlier
    sha: b5d13596f1141fac79b18d0e04bf0d5eb20b4a4e
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: work better with kapp
    sha: 478292813de11627433e939c5de5cdffa5fc1007
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: '{{ .Chart.Name }}'
  version: 0.0.71
status: {}
 
{{- end }}
